export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as Hero } from './Home/Hero'
export { default as SliderOne } from './Home/SliderOne'
export { default as TopModules } from './TopModules'
export { default as WhyChooseUs } from './WhyChooseUs'
export { default as Accounts } from './Accounts'
export { default as OprationOne } from './OprationOne'
export { default as FAQS } from './FAQS'
export { default as CtaOne } from './CtaOne'
export { default as HeroServices } from './Service/HeroServices'
export { default as ServicesGrid } from './Service/ServicesOne'
export { default as CtaTwo } from './Service/CtaTwo'
// export { default as Services } from './Service/ServicesOne'